### ISSUE TITLE
Release plans

### ISSUE THREAD

**Issue by Jc2k** [detectlabs/aioble#22]
What are your plans for aioble? Do you have a roadmap or timescale?

I'd like to be able to use this library with my home-assistant integrations (e.g. i maintain the HomeKit integration and i'd like to add a generic BLE discovery integration), but i'd need a release on PyPI to be able to do that. I think there are a few things i need to add for my needs but i wanted to make sure this project was still active first.

**Comment by kent-williams** [comment]
Hello @Jc2k, I'll get this on PyPi by the end of the week!

Please open more issues to discuss your needs, I'd be happy to make it work for you! I'm a home-assistant user myself!

I've been working on other parts of this project for a while, but I'll be returning to this in order to get it in a releasable state.

**Comment by kent-williams** [comment]
@Jc2k This is now available on PyPi.
